import { createSlice } from '@reduxjs/toolkit';

const initialState = [];

const onlineSlice = createSlice({
  name: 'online',
  initialState,
  reducers: {
    onlineUserAdded: (state, action) => {
      // Check if the user is already in the state to prevent duplicates
      if (!state.includes(action.payload)) {
        state.push(action.payload);
      }
    },
    onlineUserRemoved: (state, action) => {
      // Remove the user from the state if they are offline
      return state.filter((user) => user !== action.payload);
    },
  },
});

// Export the actions generated by createSlice
export const { onlineUserAdded, onlineUserRemoved } = onlineSlice.actions;

// Export the reducer
export default onlineSlice.reducer;
